findus:
   url: https://{customer}.findus-internet-opac.de/cgi-bin/findus.fcgi.pl?customer={customer}&leserkonto=1&submit=1
google:
   auth-uri: https://accounts.google.com/o/oauth2/auth
   token-uri: https://oauth2.googleapis.com/token
   application-name: library
http:
   timeout: PT10S
   userAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.117 Safari/537.36
   retry:
      delay: PT5S
